name: 'cn-cloud-release'
description: 'CrabNebula Cloud Release GitHub Action'
inputs:
  command:
    description: 'The command to execute using the CrabNebula Cloud CLI'
    required: true
  api-key:
    description: 'API key with write permissions for CrabNebula Cloud'
    required: true

outputs:
  stdout:
    description: "The stdout of the CLI"
    value: ${{ steps.run-command.outputs.stdout }}

runs:
  using: 'composite'

  steps:
    - name: Download CLI (unix)
      shell: bash
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        curl -L https://cdn.crabnebula.app/download/01HKMY6ZXJA3P0QHA5GQY8KKRT/latest/cn_${{ runner.os == 'Linux' && 'linux' || 'macos' }} --output cn
        chmod +x cn

    - name: Download CLI (Windows)
      shell: bash
      if: runner.os == 'Windows'
      run: |
        curl -L https://cdn.crabnebula.app/download/01HKMY6ZXJA3P0QHA5GQY8KKRT/latest/cn_windows.exe --output cn

    - name: "Run Command"
      id: run-command
      shell: bash
      env:
        CN_API_KEY: ${{ inputs.api-key }}
      run: |
        OUTPUT=$(./cn ${{ inputs.command }})
        echo "stdout<<nEOFn" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "nEOFn" >> $GITHUB_OUTPUT

