name: 'cn-cloud-release'
description: 'CrabNebula Cloud Release GitHub Action'
inputs:
  command:
    description: 'The command to execute using the CrabNebula Cloud CLI'
    required: true
  api-key:
    description: 'API key with write permissions for CrabNebula Cloud'
    required: true
  path:
    description: 'Optional path to a directory where the CLI should be downloaded, needs to be a valid path (Unix syntax)'
    required: false
    default: '.'
  working-directory:
    description: 'Current working directory to use when running the CLI'
    required: false
    default: '.'

outputs:
  stdout:
    description: "The stdout of the CLI"
    value: ${{ steps.run-command.outputs.stdout }}

runs:
  using: 'composite'
  steps:
    - name: Get current date
      shell: bash
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      if: runner.os == 'Linux' || runner.os == 'macOS'

    - name: Get current date
      shell: pwsh
      if: runner.os == 'Windows'
      run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

#    - name: Cache CLI
#      id: restore-cache
#      uses: actions/cache/restore@v4
#      with:
#        path: ${{ inputs.path }}/cn
#        key: ${{ runner.os }}-${{ runner.arch }}-cn-${{ env.CURRENT_DATE }}

    - name: Download CLI (Linux)
      id: download-cn-cli
      shell: bash
      if: steps.restore-cache.outputs.cache-hit != 'true' && runner.os == 'Linux'
      working-directory: ${{ inputs.path }}
      run: |
        : Download CLI
        echo "Downloading CLI..."
        if [[ "${{ runner.arch }}" == "X64" ]]; then
          curl -L https://cdn.crabnebula.app/download/crabnebula/cn-cli/latest/platform/linux-binary-x86_64 --output cn
        else
          curl -L https://cdn.crabnebula.app/download/crabnebula/cn-cli/latest/platform/linux-binary-aarch64 --output cn
        fi
        chmod +x cn
        echo "cn-path=$(realpath cn)" >> $GITHUB_OUTPUT

    - name: Download CLI (macOS)
      id: download-cn-cli
      shell: bash
      if: steps.restore-cache.outputs.cache-hit != 'true' && runner.os == 'macOS'
      working-directory: ${{ inputs.path }}
      run: |
        : Download CLI
        echo "Downloading CLI..."
        curl -L https://cdn.crabnebula.app/download/crabnebula/cn-cli/latest/platform/darwin-binary-universal --output cn
        chmod +x cn
        echo "cn-path=$(realpath cn)" >> $GITHUB_OUTPUT

    - name: Download CLI (Windows)
      id: download-cn-cli
      shell: bash
      if: steps.restore-cache.outputs.cache-hit != 'true' && runner.os == 'Windows'
      working-directory: ${{ inputs.path }}
      run: |
        : Download CLI
        echo "Downloading CLI..."
        curl -L https://cdn.crabnebula.app/download/crabnebula/cn-cli/latest/platform/windows-binary-x86_64 --output cn
        echo "cn-path=$(realpath cn)" >> $GITHUB_OUTPUT

#    - uses: actions/cache/save@v4
#      continue-on-error: true
#      with:
#        path: ${{ inputs.path }}/cn
#        key: ${{ steps.restore-cache.outputs.cache-primary-key }}

    - name: "Run Command"
      id: run-command
      shell: bash
      env:
        CN_API_KEY: ${{ inputs.api-key }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        : cn ${{ inputs.command }}
        echo "running `${{ steps.download-cn-cli.outputs.cn-path }}` from '${{ inputs.working-directory }}'"
        exec 5>&1
        OUTPUT=$(${{ steps.download-cn-cli.outputs.cn-path }} ${{ inputs.command }} | tee >(cat - >&5))
        echo "stdout<<nEOFn" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "nEOFn" >> $GITHUB_OUTPUT
