name: 'cn-cloud-release'
description: 'CrabNebula Cloud Release GitHub Action'
inputs:
  command:
    description: 'The command to execute using the CrabNebula Cloud CLI'
    required: true
  api-key:
    description: 'API key with write permissions for CrabNebula Cloud'
    required: true
  path:
    description: 'Optional path to a directory where the CLI should be downloaded, needs to be a valid path (Unix syntax)'
    required: false
    default: '.'

outputs:
  stdout:
    description: "The stdout of the CLI"
    value: ${{ steps.run-command.outputs.stdout }}

runs:
  using: 'composite'
  steps:
    - name: Download CLI (Linux)
      shell: bash
      if: runner.os == 'Linux'
      run: |
        cd ${{ inputs.path }}
        ARCH=$(uname -m)
        if [[ "$ARCH" == "x86_64" ]]; then
          curl -L https://cdn.crabnebula.app/download/crabnebula/cn-cli/latest/platform/linux-binary-x86_64 --output cn
        else
          curl -L https://cdn.crabnebula.app/download/crabnebula/cn-cli/latest/platform/linux-binary-aarch64 --output cn
        fi
        chmod +x cn

    - name: Download CLI (macOS)
      shell: bash
      if: runner.os == 'macOS'
      run: |
        cd ${{ inputs.path }}
        curl -L https://cdn.crabnebula.app/download/crabnebula/cn-cli/latest/platform/darwin-binary-universal --output cn
        chmod +x cn

    - name: Download CLI (Windows)
      shell: bash
      if: runner.os == 'Windows'
      run: |
        cd ${{ inputs.path }}
        curl -L https://cdn.crabnebula.app/download/crabnebula/cn-cli/latest/platform/windows-binary-x86_64 --output cn

    - name: "Run Command"
      id: run-command
      shell: bash
      env:
        CN_API_KEY: ${{ inputs.api-key }}
      run: |
        cd ${{ inputs.path }}
        exec 5>&1
        OUTPUT=$(./cn ${{ inputs.command }} | tee /dev/fd/5)
        echo "stdout<<nEOFn" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "nEOFn" >> $GITHUB_OUTPUT
