name: 'cn-cloud-release'
description: 'CrabNebula Cloud Release GitHub Action'
inputs:
  command:
    description: 'The command to execute using the CrabNebula Cloud CLI'
    required: true
  api-key:
    description: 'API key with write permissions for CrabNebula Cloud'
    required: true

outputs:
  stdout:
    description: "The stdout of the CLI"
    value: ${{ steps.run-command.outputs.stdout }}

runs:
  using: 'composite'

  steps:
    - name: Download CLI (unix)
      shell: bash
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        curl https://cdn.crabnebula.app/asset/${{ fromJson('{ "Linux": "01HKNKYBKNQWZT5A89CT9GDZXX", "macOS": "01HKNKYECKV6TX1XD40AF67X7N" }')[runner.os] }} --output cn
        chmod +x cn

    - name: Download CLI (Windows)
      shell: bash
      if: runner.os == 'Windows'
      run: |
        curl https://cdn.crabnebula.app/asset/01HKNKYGPMY5BT70R952AKX33A --output cn

    - name: "Run Command"
      id: run-command
      shell: bash
      env:
        CN_API_KEY: ${{ inputs.api-key }}
      run: |
        OUTPUT=$(./cn ${{ inputs.command }})
        echo "stdout<<nEOFn" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "nEOFn" >> $GITHUB_OUTPUT

