name: Test Action

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: get CLI version
        uses: ./
        id: version
        with:
          command: --version

      - name: echo outputs
        run: echo '${{ steps.version.outputs.stdout }}'
