name: Test Action

on:
  workflow_dispatch:
    inputs:
      api-key:
        type: string
        description: Cloud API key
        required: true
      cn-env:
        description: Cloud environment
        default: qa
        type: choice
        options:
          - qa
          - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CN_API_KEY: ${{ inputs.api-key }}
  CN_ENV: ${{ inputs.cn-env }}

jobs:
  draft:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: whoami
        uses: ./
        id: whoami
        with:
          command: release whoami
          api-key: ${{ env.CN_API_KEY }}

      - name: echo outputs
        run: echo '${{ steps.whoami.outputs.stdout }}'
