name: Test Action

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "action.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: get CLI version
        uses: ./
        id: version
        with:
          command: --version

      - name: echo outputs
        run: echo '${{ steps.version.outputs.stdout }}'

      - name: get CLI version (different cwd)
        uses: ./
        with:
          command: --version
          working-directory: .changes
